site_name: Open Camera
site_description: 
site_url: https://open-camera-app.readthedocs.io

docs_dir: docs

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Features: features.md
  - How to Download: how-to-download.md
  - FAQ: faq.md
  - Open Camera Laptop: open-camera-laptop.md
  - Open Camera App Windows: open-camera-app-windows.md
  - Open Camera Hp Laptop: open-camera-hp-laptop.md
  - Open Camera Macbook: open-camera-macbook.md
  - Open Camera App Android: open-camera-app-android.md
